version: "2"
services:
  web:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - db-data:/usr/data/db

volumes:
  db-data:
