name: Deploy AWS CDK

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Remove Old Files
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./cdk-savvy/app.zip

      - name: Zip SavvApp
        uses: montudor/action-zip@v1
        with:
          args: zip -r ./cdk-savvy/app.zip ./*

      - name: CDK Synth
        run: cdk synth
        working-directory: cdk-savvy

      - name: CDK Deploy
        run: cdk deploy
        working-directory: cdk-savvy
