name: Secret Example

on:
  pull_request:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_REGION: 
        required: true
      ROLE_TO_ASSUME:
        required: true

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "AWS REGION"
          echo ${{ secrets.AWS_REGION }}
          echo " TESTING ...."
          echo "ROLE SECRET:"
          echo ${{ secrets.ROLE_TO_ASSUME}} | sed 's/./% /g'
