name: Secret Example

on:
  pull_request:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "AWS REGION"
          echo ${{ secrets.AWS_REGION }}
          echo " TESTING ...."
          echo "ROLE SECRET:"
          echo ${{ secrets.ROLE_TO_ASSUME}} | sed 's/./% /g'
